### ISSUE TITLE
Error in Losses.md notebook

### ISSUE THREAD

**Issue by matthew-brett** [regreg/regreg#23]
I am just now running through the notebook examples.  In `Losses.md`, I get this error:

```
------------------
problem = rr.simple_problem(quadratic, hinge_loss)
solver = rr.FISTA(problem)
vals = solver.fit()
solver.composite.coefs
------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-64-82e5a9292d8d> in <module>()
----> 1 problem = rr.simple_problem(quadratic, hinge_loss)
      2 solver = rr.FISTA(problem)
      3 vals = solver.fit()
      4 solver.composite.coefs

/Users/mb312/dev_trees/regreg/regreg/problems/simple.pyc in __init__(self, smooth_atom, proximal_atom)
     20         self.smooth_atom = smooth_atom
     21         self.proximal_atom = proximal_atom
---> 22         self.coefs = self.smooth_atom.coefs = self.proximal_atom.coefs
     23 
     24     def smooth_objective(self, x, mode='both', check_feasibility=False):

AttributeError: 'affine_atom' object has no attribute 'coefs'
```

`self.proximal_atom` does not have a `coefs` attribute.  Does this ring any bells?

By the way - I'm testing with `make notebooks` in my `markdown-builder` branch, that is the basis for PR #21.

**Comment by jonathan-taylor** [comment]
Thanks. Will look into it.

On Thu, Apr 7, 2016 at 12:10 PM, Matthew Brett <notifications@github.com>
wrote:

> I am just now running through the notebook examples. In Losses.md, I get
> this error:
>
> ------------------
> problem = rr.simple_problem(quadratic, hinge_loss)
> solver = rr.FISTA(problem)
> vals = solver.fit()
> solver.composite.coefs
> ------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-64-82e5a9292d8d> in <module>()
> ----> 1 problem = rr.simple_problem(quadratic, hinge_loss)
>       2 solver = rr.FISTA(problem)
>       3 vals = solver.fit()
>       4 solver.composite.coefs
>
> /Users/mb312/dev_trees/regreg/regreg/problems/simple.pyc in __init__(self, smooth_atom, proximal_atom)
>      20         self.smooth_atom = smooth_atom
>      21         self.proximal_atom = proximal_atom
> ---> 22         self.coefs = self.smooth_atom.coefs = self.proximal_atom.coefs
>      23
>      24     def smooth_objective(self, x, mode='both', check_feasibility=False):
>
> AttributeError: 'affine_atom' object has no attribute 'coefs'
>
> self.proximal_atom does not have a coefs attribute. Does this ring any
> bells?
>
> By the way - I'm testing with make notebooks in my markdown-builder
> branch, that is the basis for PR #21
> <https://github.com/regreg/regreg/pull/21>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/regreg/regreg/issues/23>
>



-- 
Jonathan Taylor
Dept. of Statistics
Sequoia Hall, 137
390 Serra Mall
Stanford, CA 94305
Tel:   650.723.9230
Fax:   650.725.8977
Web: http://www-stat.stanford.edu/~jtaylo

**Comment by jonathan-taylor** [comment]
This code should not work as written because the hinge_loss does not have a simple proximal operator. 

I will go through these examples to get working properly.

**Comment by matthew-brett** [comment]
Maybe another day in BIDS to get this finished up?  I think the notebook build machinery is in there, but needs some refining under the expert eyes of Brett and Stefan.

**Comment by jonathan-taylor** [comment]
Sounds like a good idea. Maybe in two weeks' time? (Which is again a week
that I won't be teaching)

On Wed, Apr 20, 2016 at 11:39 AM, Matthew Brett <notifications@github.com>
wrote:

> Maybe another day in BIDS to get this finished up? I think the notebook
> build machinery is in there, but needs some refining under the expert eyes
> of Brett and Stefan.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/regreg/regreg/issues/23#issuecomment-212552149>
>



-- 
Jonathan Taylor
Dept. of Statistics
Sequoia Hall, 137
390 Serra Mall
Stanford, CA 94305
Tel:   650.723.9230
Fax:   650.725.8977
Web: http://www-stat.stanford.edu/~jtaylo

**Comment by matthew-brett** [comment]
Ah - I didn't think that through properly.  I will probably go to Cuba next Thursday or so, but I can show y'all what I did and where I think the problems are, so you can fix it without me.

**Comment by jonathan-taylor** [comment]
This example has been reworked in the Losses.rst where we use a huberized SVM
