### ISSUE TITLE
https://pypi.org/project/regreg/ is broken?

### ISSUE THREAD

**Issue by Sandy4321** [regreg/regreg#42]
great code 
but how to install it
since link
https://pypi.org/project/regreg/
is broken?

**Comment by jonathan-taylor** [comment]
Can you try again?

**Comment by Sandy4321** [comment]
no version for Windows?
![image](https://user-images.githubusercontent.com/11426119/64044732-89f8cd00-cb35-11e9-8f3d-a137ffc18d54.png)

**Comment by Sandy4321** [comment]
Microsoft Windows [Version 10.0.17763.678]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>pip install regreg
Collecting regreg
  Could not find a version that satisfies the requirement regreg (from versions: )
No matching distribution found for regreg

C:\WINDOWS\system32>

**Comment by Sandy4321** [comment]
seems to be your is the best world wide, it is really bad  luck that it can not be installed :(

**Comment by jonathan-taylor** [comment]
Will look into how to build for windows

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthew-brett** [comment]
I can have a go at that if you like.

**Comment by matthew-brett** [comment]
Jonathan - there's a template at
<https://github.com/MacPython/pywavelets-wheels/blob/master/appveyor.yml>
if you want to do it yourself.

**Comment by jonathan-taylor** [comment]
Windows wheels now on pip

**Comment by Sandy4321** [comment]
great ! installation works , will try how to use it
do you have idea what is the best way to use for sparse one hot unbalanced data?
is L1 regularization the best ?
and there are many correlated features - multicollinearity 
so 
1
values are only ones or zeros
like
010010010
010010100
000100100
100010000

2
number of ones is much less than number of zeros
3
two labels target is strongly biased towards on of labels 
for example
yes no no no no no yes no no no no
4
multicollinearity 

Thanks again, good job!!!!!

 


Microsoft Windows [Version 10.0.17763.737]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\Torah>pip install regreg
Collecting regreg
  Downloading https://files.pythonhosted.org/packages/f5/7b/f66a30da4e6e7a9f55eea92552365a00c770ea0aeb297788f340173def2d/regreg-0.1.3-cp36-none-win_amd64.whl (281kB)
    100% |████████████████████████████████| 286kB 3.8MB/s
Requirement already satisfied: Cython>=0.18 in c:\users\sndr\anaconda3\lib\site-packages (from regreg) (0.27.3)
Installing collected packages: regreg
Successfully installed regreg-0.1.3

**Comment by jonathan-taylor** [comment]
The package does not offer recommendations on methodology per se, just functions to solve these problems once posed. Literature may  point to good regularizers for your problem.
________________________________
