### ISSUE TITLE
Error for installation of the regreg package

### ISSUE THREAD

**Issue by ruanhq** [regreg/regreg#60]
Hi Dr.Taylor

I'm trying to install the regreg package, however in the installation stage, there are following errors:(my python version is 3.12)

----------------------------------------------------------------------------
Error compiling Cython file:
------------------------------------------------------------
...
    g_l1 = grad[l1_penalty]
    if g_l1.shape not in [(), (0,)]:

        failing[l1_penalty] += np.fabs(g_l1) > lagrange * (1 + tol)
        if debug:
            print 'l1 (dual) feasibility:', np.fabs(g_l1) > lagrange * (1 + tol), np.fabs(g_l1), lagrange * (1 + tol)
                  ^
------------------------------------------------------------regreg/atoms/mixed_lasso_cython.pyx:184:18: Syntax error in simple statement list

non-existing path in 'regreg/atoms': 'mixed_lasso_cython.c'
----------------------------------------------------------------------------

May I kindly consult about how to resolve this issue?

Thanks!!

**Comment by jonathan-taylor** [comment]
This print​ statement needs to be upgraded to python3
________________________________
